version: "3"
services:
  api:
    build: 42API/
    image: 42api
    restart: always
    ports:
      - ${API_PORT:-3003}:${API_PORT:-3003}
    environment:
      - UID=${APPUID}
      - SECRET=${SECRET}
      - PORT=${API_PORT:-3003}
    volumes:
      - segbotApiData:/api/data
  segbot:
    build: discord/
    image: segbot
    restart: always
    links:
      - api
    ports:
      - ${SEGBOT_PORT:-8008}:${SEGBOT_PORT:-8008}
    environment:
      - APPUID=${APPUID}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DEV_CHANNEL=${BOT_DEV_CHANNEL}
      - SEGBOT_PORT=${SEGBOT_PORT:-8008}
      - API_PORT=${API_PORT}
      - APP_HOST=${APP_HOST}
      - API_HOST=api
    volumes:
      - segbotData:/segbot/data
  checker:
    build: APICheck/
    image: checker
    restart: always
    links:
      - api
      - segbot
    environment:
      - SEGBOT_URL=http://segbot:${SEGBOT_PORT:-8008}
      - UID=${APPUID}
      - SECRET=${SECRET}
      - USER_API_URL=http://api:${API_PORT}
volumes:
  segbotData: {}
  segbotApiData: {}
