version: "3"
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbData:/data/db
  api:
    build: 42API/
    image: 42api
    restart: always
    links:
      - db
    ports:
      - ${API_PORT}:3000
    environment:
      - DB_NAME=users
      - DB_URL=db
      - UID=${APPUID}
      - SECRET=${SECRET}
      - PORT=${API_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
  segbot:
    build: discord/
    image: segbot
    restart: always
    links:
      - api
    ports:
      - ${SEGBOT_PORT}:8000
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DEV_CHANNEL=${BOT_DEV_CHANNEL}
      - API_PORT=${API_PORT}
      - API_HOST=api
    volumes:
      - segbotData:/segbot/data
  checker:
    build: APICheck/
    image: checker
    restart: always
    links:
      - api
      - segbot
    environment:
      - SEGBOT_URL=http://segbot:${SEGBOT_PORT}
      - UID=${APPUID}
      - SECRET=${SECRET}
      - USER_API_URL=http://api:${API_PORT}
volumes:
  segbotData: {}
  dbData: {}
