version: "3"
services:
  api:
    build: 42API/
    image: 42api
    restart: always
    ports:
      - ${API_PORT}:3000
    environment:
      - DB_NAME=users
      - DB_URL=${DB_URL}
      - UID=${APPUID}
      - SECRET=${SECRET}
      - PORT=${API_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
  segbot:
    build: discord/
    image: segbot
    restart: always
    links:
      - api
    ports:
      - ${SEGBOT_PORT}:8000
    environment:
      - APPUID=${APPUID}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DEV_CHANNEL=${BOT_DEV_CHANNEL}
      - SEGBOT_PORT=${SEGBOT_PORT}
      - API_PORT=${API_PORT}
      - APP_HOST=${APP_HOST}
      - API_HOST=api
    volumes:
      - segbotData:/segbot/data
  checker:
    build: APICheck/
    image: checker
    restart: always
    links:
      - api
      - segbot
    environment:
      - SEGBOT_URL=http://segbot:${SEGBOT_PORT}
      - UID=${APPUID}
      - SECRET=${SECRET}
      - USER_API_URL=http://api:${API_PORT}
volumes:
  segbotData: {}