name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        env:
          API_PORT: ${{ piscibotReloaded.API_PORT }}
          APPUID: ${{ piscibotReloaded.APPUID }}
          APP_HOST: ${{ piscibotReloaded.APP_HOST }}
          BOT_DEV_CHANNEL: ${{ piscibotReloaded.BOT_DEV_CHANNEL }}
          BOT_TOKEN: ${{ piscibotReloaded.BOT_TOKEN }}
          DB_PASSWORD: ${{ piscibotReloaded.DB_PASSWORD }}
          DB_URL: ${{ piscibotReloaded.DB_URL }}
          DB_USERNAME: ${{ piscibotReloaded.DB_USERNAME }}
          SECRET: ${{ piscibotReloaded.SECRET }}
          SEGBOT_PORT: ${{ piscibotReloaded.SEGBOT_PORT }}
        run: echo $API_PORT && echo $SEGBOT_PORT && docker-compose build
        
      - name: Deploy
        env:
          API_PORT: ${{ piscibotReloaded.API_PORT }}
          APPUID: ${{ piscibotReloaded.APPUID }}
          APP_HOST: ${{ piscibotReloaded.APP_HOST }}
          BOT_DEV_CHANNEL: ${{ piscibotReloaded.BOT_DEV_CHANNEL }}
          BOT_TOKEN: ${{ piscibotReloaded.BOT_TOKEN }}
          DB_PASSWORD: ${{ piscibotReloaded.DB_PASSWORD }}
          DB_URL: ${{ piscibotReloaded.DB_URL }}
          DB_USERNAME: ${{ piscibotReloaded.DB_USERNAME }}
          SECRET: ${{ piscibotReloaded.SECRET }}
          SEGBOT_PORT: ${{ piscibotReloaded.SEGBOT_PORT }}
        run: docker-compose up -d
