name: Docker Build 42API

on:
  push:
    branches: [ 42api, master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build 42API
        run: (cd ./42API ; docker build . --tag api:$(date +%s))