name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Checker
      run: (cd ./APICheck ; docker build . --tag checker:$(date +%s))
    - name: Build Segbot
      run: (cd ./discord ; docker build . --tag segbot:$(date +%s))
    - name: Build API
      run: (cd ./42API ; docker build . --tag api:$(date +%s))
