name: Docker Build Checker

on:
  push:
    branches: [ devel, master ]
  pull_request:
    branches: [ devel, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Checker
        run: (cd ./APICheck ; docker build . --tag checker:$(date +%s))