name: Go Build Segbot

on:
  push:
    branches: [devel, master]
  pull_request:
    branches: [devel]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build Segbot
        run: (cd ./discord/segbot ; go install .)
