name: Go Build 42API

on:
  push:
    branches: [ devel, master ]
  pull_request:
    branches: [ devel, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build 42API
        run: (cd ./42API/api ; go install .)