name: Go Build Checker

on:
  push:
    branches: [ checker, master ]
  pull_request:
    branches: [ checker ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build Checker
        run: (cd ./APICheck/checker ; go install .)